on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: Set image tag
          id: vars
          run: echo "IMAGE_TAG=v${{ github.run_number }}" >> $GITHUB_ENV

        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/apa-backend:${{ env.IMAGE_TAG }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/apa-backend:${{ env.IMAGE_TAG }}

        - name: Deploy to Server
          uses: appleboy/ssh-action@v0.1.5
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USERNAME }}
            key: ${{ secrets.SERVER_SSH_KEY }}
            script: |
              # Get current backend tag from docker-compose.yml
              CURRENT_TAG=$(grep -o 'apa-backend:v[0-9]*' docker-compose.yml | head -1)
              NEW_TAG="apa-backend:${{ env.IMAGE_TAG }}"
              
              # Only update and restart if tag has changed
              if [ "$CURRENT_TAG" != "$NEW_TAG" ]; then
                echo "Updating from $CURRENT_TAG to $NEW_TAG"
                # Update docker-compose.yml with new backend tag
                sed -i "s|apa-backend:v[0-9]*|$NEW_TAG|g" docker-compose.yml
                # Pull new images and restart services
                docker-compose pull
                docker-compose up -d
                echo "Deployment completed successfully"
              else
                echo "No changes detected. Current tag: $CURRENT_TAG"
              fi
